"use strict";
const msg = {
  inputErrors: "Input errors",
  loginIdInvalid: "loginId is invalid",
  loginIdRequired: "loginId is required",
  passwordInvalid: "password is invalid",
  passwordRequired: "password is required",
  passwordIncorrect: "password is incorrect",
  codeInvalid: "code is invalid",
  codeRequired: "code is required",
  mobileInvalid: "mobile is invalid",
  mobileRequired: "mobile is required",
  firstNameInvalid: "firstName is invalid",
  firstNameRequired: "firstName is requried",
  lastNameInvalid: "lastName is invalid",
  lastNameRequired: "lastName is requried",
  emailInvalid: "email is invalid",
  emailRequired: "email is required",
  emailAlreadyTaken: "Email already exist",
  usernameInvalid: "username is invalid",
  usernameRequired: "username is required",
  usernameAlreadyTaken: "username is already taken",
  userAlreadyExist: "User already exist",
  userNotFound: "user with not found",
  tokenInvalid: "Token invalid",
  tokenRequired: "Token is required",
  tokenExpired: "Token you provided has expired",
  tokenIncorrect: "Token incorrect",
  successlfullogIn: "successfully logedin",
  verficationTokenSent: "Verification code was sent on verified medium",
  mediaNotSupported: "Media not supported",
  mediaRequired: "required media",
  paswordResetSuccess: "Passwordwas sucessfully reset",
  confirmPasswordRequired: "confirm password required",
  confirmPasswordInvalid: "confrim password invalid",
  pAndCpMismatch: "Password and confirm password dont match",
  resetPasswordSuccess: "Reset password success",
  getRight: "rights found",
  rolesNotFound: "Roles not found",
  rolesFound: "Roles found in sytem",
  roleRightsUpdated: "rights updated for the role",
  deleteRoleSuccess: "Delete role success",
  oneSuperAdmin: "Only one super admin allowed by system",
  userRoleUpdated: "updated user role",
  successCreateRole: "role created successfuly",
  roleNotFound: "role not found in system",
  roleFound: "role found in sysyem",
  roleAlreadyExist: "role already exist",
  roleIdInvalid: "roleId is invalid",
  roleIdRequired: "roleId is required",
  userIdInvalid: "userId is invalid",
  userIdRequired: "userId is required",
  roleNotRecognized: "role not recognized",
  roleRequired: "role is required"
};
module.exports = msg;
